# Generated by Django 4.1.7 on 2023-03-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='img2',
            field=models.FileField(blank=True, default=None, upload_to='static/images/user_images'),
        ),
    ]
