# Generated by Django 4.1.7 on 2023-02-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_box_alter_user_email_alter_user_nick_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='length',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='width',
            new_name='lon',
        ),
    ]
