# Generated by Django 4.1.7 on 2023-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_box_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
