# Generated by Django 4.1.7 on 2023-02-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_length_box_lat_rename_width_box_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='img2',
            field=models.FileField(null=True, upload_to='static/images/user_images'),
        ),
    ]
