# Generated by Django 4.1.7 on 2023-03-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_box_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='static/images/user_images'),
        ),
        migrations.AlterField(
            model_name='box',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='static/images/user_images'),
        ),
    ]
